### ISSUE TITLE
Login form shows incorrect validation after login

### ISSUE THREAD

**Issue by abhishekkumar08** [openMF/online-banking#26]
**Describe the bug**
Whenever we login into the app with username and password the login form shows validation error even with correct credentials.

**To Reproduce**
1. Run the app.
2. Login with correct credentials
3. The input fields turns red.

**Expected behavior**
Wrong valildation error

**Actual behavior**
The form should login without any error.

**Screenshots**
Expected
![Correct_login](https://user-images.githubusercontent.com/59651136/104226679-378c2800-546e-11eb-9d0c-f0fb7c49bcac.gif)

Actual
![Incorrect_login](https://user-images.githubusercontent.com/59651136/104226698-3f4bcc80-546e-11eb-8bce-39f9822a5688.gif)

I have resolved this issue and would be submitting a PR

**Comment by abhishekkumar08** [comment]
@manigedit Please review this. Thanks!

**Comment by manigedit** [comment]
@abhishekkumar08 Please share a final screencast of the pic in this conversation

**Comment by abhishekkumar08** [comment]
![Online Banking — Mozilla Firefox 2021-01-12 15-29-25](https://user-images.githubusercontent.com/59651136/104304084-ef621980-54f0-11eb-9ad1-c84d5c9f3759.gif)
@manigedit Please have a look.
